export const CUISINE_LIST_REQUEST = 'CUISINE_LIST_REQUEST';
export const CUISINE_LIST_SUCCESS = 'CUISINE_LIST_SUCCESS';
export const CUISINE_LIST_FAILURE = 'CUISINE_LIST_FAILURE'
export const CUISINE_DETAILS_REQUEST = 'CUISINE_DETAILS_REQUEST';
export const CUISINE_DETAILS_SUCCESS = 'CUISINE_DETAILS_SUCCESS';
export const CUISINE_DETAILS_FAILURE = 'CUISINE_DETAILS_FAILURE'

