
export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST';
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS';
export const RESTAURANT_LIST_FAILURE = 'RESTAURANT_LIST_FAILURE'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST';
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS';
export const RESTAURANT_DETAILS_FAILURE = 'RESTAURANT_DETAILS_FAILURE'